<?php

namespace App\Booking\Application\Command;

use App\Booking\Domain\CustomerName;
use App\Booking\Domain\Email;
use App\Booking\Domain\Reservation;
use App\Booking\Domain\ReservationRepository;
use Psr\Clock\ClockInterface;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler(bus: 'command.bus')]
final class CreateReservationHandler
{
    public function __construct(
        private readonly ReservationRepository $reservations,
        private readonly ClockInterface $clock,
    ) {
    }

    /**
     * Returns the new reservation's id (ids are generated by the database).
     */
    public function __invoke(CreateReservation $command): int
    {
        $reservation = Reservation::book(
            CustomerName::fromString($command->customerName),
            Email::fromString($command->email),
            $command->reservationDate,
            $this->clock->now(),
        );

        $this->reservations->save($reservation);

        return $reservation->id();
    }
}
